name: CI

on: 
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - master

jobs:
  deploy: 
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Push to kharis.timapp.id
        uses: appleboy/ssh-action@master
        with:
          host: kharis.timapp.id
          username: ${{ secrets.DEFAULT_SERVER_USERNAME }}
          password: ${{ secrets.DEFAULT_SERVER_PASSWORD }}
          script: 
            cd /var/www/html/app  && 
            git pull origin main && 
            git status && 
            chmod 775 /var/www/html/app/storage/logs/ &&
            chmod 775 /var/www/html/app/storage/framework/views/ &&
            chmod 775 /var/www/html/app/storage/framework/sessions/ &&
            chmod 775 /var/www/html/app/storage/logs/


